#pragma once

#define APP_BUTTON_SCAN_MS 10
#define APP_BUTTON_DEBOUNCE_MS 30
#define APP_BUTTON_DOUBLE_CLICK_MS 300
#define APP_BUTTON_LONG_PRESS_MS 800
#define APP_BUTTON_RIGHT_MODE_MS 500
#define APP_BUTTON_RIGHT_POWER_MS 1000
